### PR TITLE
CAdES: Updating SignerAttributes to SignerAttributesV2 as specified by ETSI

### PR DESCRIPTION
**Pull request by SebastianSchuberth**
ETSI EN 319 122-1 V1.1.1 (2016-04) (see: http://www.etsi.org/deliver/etsi_en/319100_319199/31912201/01.01.01_60/en_31912201v010101p.pdf, chapter 5.2.6.1 ) now allows for the inclusion of signed assertions into SignerAttributes for a CAdES signature. This however requires the now deprecated attribute to be replaced by the newer version SignerAttributesV2 as specified in the document. Unfortunately Bouncy Castle does not yet support this new version, so I tried to do it myself.

### CODE REVIEW

**Comment by SebastianSchuberth** [comment]
Currently CertifiedAttributesV2 is not yet implemented, see TODO in SignerAttributeV2Factory, since I'm not sure how to build an AttributeCertificate object from a mere list of Strings.

**Comment by pvandenbroucke** [comment]
Hello Sebastian,

Thanks for your proposal. I will have a look in the following days. 

Could you check again your commits ? It seems not complete. I get a compilation error because a change is missing in the class BLevelParameters.

Regards,

Pierrick

**Comment by SebastianSchuberth** [comment]
Hello Pierrick, 

you were right, the commit for BLevelParameters was missing, I've added it now.

Best Regards,
Sebastian

**Comment by pvandenbroucke** [comment]
Hello Sebastian,

I analysed your proposal. Unfortunately, I can't integrate it for some reasons : 

- The signer-attributes-v2 attribute shall not be present if it is empty ; 
- If a PAdES signature is created, it should be included (see ETSI EN 319 142-1 V1.1.1 chapter 5.2) ; 
- The OtherAttributeCertificate and SignedAssertions are not clearly defined in the standard ; 
- The validation should support both standards (ETSI TS 101 733 and EN 319 122) ; 
- (Unit tests are missing.)
	
What I propose is to implement the signer-attributes-v2 attribute and its clearly defined properties. I prefer to avoid adding unclear properties (which could be wrongly interpreted).

Could you tell me how did you plan to use these properties in your signatures ? 

Thanks in advance,

Regards,

Pierrick

**Comment by SebastianSchuberth** [comment]
Hello Pierrick,

thank you for your quick analysis. Commenting on your reasons (from top to bottom): 

1. Should probably be fixed easily in CAdESLevelBaselineB (check for empty attributes and/or null) and through some adjustments in the SignerAttributeV2 factory  
2. I think the deletion of the padesusage check should be enough for that (if not, maybe you could elaborate a bit more on what you meant)
3. I totally understand your concern about the not clearly defined attribute (OtherAttributeCertificate) and I agree with you that it should be omitted until it is properly defined in the standard. This means that until then we won't really have use of CertifiedAttributesV2 and can keep AttributeCertficate (which is not yet implemented from what I've seen).
About SignedAssertions: "The definition of specific signedAssertions is outside of the scope of the present document. Any assertion encapsulated within this sequence shall be signed by third party. NOTE 4:  A possible content of such a qualifier can be a signed SAML assertion, see of SAML[18]" (EN 319 122-1). From my understanding this means that it just holds a signed SAML assertion, which is all we would need (see below for planned use case).  
4. If you mean getCertifiedSignerRoles() and getClaimedSignerRoles() in the CAdESSignature class should also work for old SignerAttributes, then I must admit I hadn't thought of that and they should be included like you said.  
5. To be honest I first wanted to have your opinion on this request before I write tests for it. 

For my plan with this pull request: 
We have a use case where the user wants to sign a PDF (with PAdES profile) by uploading it to our signing server. The PDF is signed via the server key, but to ensure that this specific user was the one triggering this signature/seal, they have to authenticate themselves at an IdP beforehand. The IdP sends a signed SAML assertion to the signing server, which then incorporates the assertion into the PAdES signature via the signed-attributes-v2. 

So the implementation of signed-attributes-v2 would then include only SignedAssertions (holding signed SAML assertions), the claimed attributes which have already been implemented by you for the old SignedAttributes and a factory for convenient creation of a signed-attribute-v2. 

Let me know what you think about my points/ideas and if you have more questions about the use case, feel free to ask.

Thanks in advance!

Best Regards,
Sebastian

**Comment by pvandenbroucke** [comment]
Hello Sebastian,

Thanks for your reply. Your use case is really interesting. I'll search for more details on the SAML assertions (format in CAdES/XAdES).

I propose to work together on your branch to improve the above points and add the SAML assertions.

Regards,

Pierrick

**Comment by pvandenbroucke** [comment]
Hello Sebastian,

I pushed my last modifications.

I prefer to add the SAML assertion as specified in the standard : 

> The claimed-SAML-assertion may be used in a claimedAttributes field of the signer-attributesv2
attribute. It shall not be used anywhere else. 

I removed the OtherAttributeCertificate and SignedAssertions properties and added a warning.

I also moved the SAMLAssertion parameter in the CAdESSignatureParameters (which is inherited in PAdES). I will move it back in the BLevelParameters when the implementation is done in XAdES (more complicated with the additional namespaces and the canonicalization).

Could you have a look and give me a feedback ? 

I also sent some samples to ETSI experts to get opinions.

Regards,

Pierrick

**Comment by SebastianSchuberth** [comment]
Hello Pierrick,

thank your for your interest in our use case and your contributions to it. Regarding the feedback you asked for: 

>I prefer to add the SAML assertion as specified in the standard :

>> The claimed-SAML-assertion may be used in a claimedAttributes field of the signer-attributesv2 attribute. It shall not be used anywhere else.

>I removed the OtherAttributeCertificate and SignedAssertions properties and added warnings. 

There seems to be a misunderstanding. The semantics of including a claimed-SAML-assertion attribute (clause 5.2.6.2)  within SignerAttributeV2.claimedAttributes is different from the semantics
of including a SignedAssertion  within SignerAttributesV2.signedAssertions. This difference is highlighted within NOTE 3 in Section 5.2.6.1:
>NOTE 3: A signed assertion is stronger than a claimed attribute, since a third party asserts with a signature that the attribute of the signer is valid. However, it may be less restrictive than an attribute certificate

Therefore SD-DSS should in the end support both. Furthermore, as EN 319
122-1 does not specify the set of possible or admissible OIDs which go into signedAssertionID, SD-DSS should somehow allow to  set a specific OID within the signature generation and the validation procedure should on the other side allow to get the OID.

Best Regards
Sebastian

**Comment by pvandenbroucke** [comment]
Hello Sebastian,

I understand your point of view. 

I think that the code implements one of the possibilities that the majority of tools could be able to interpret. Technically, if I set the assertion in the claimedAttributes field or in the signedAssertions field, both of them are protected by the signature. The embedded SAML assertion will need to be parsed,... in a post-treatment.

The assertion is clearly defined in the claimedAttribute with this given OID : 

> id-aa-ets-claimedSAML OBJECT IDENTIFIER ::= { itu-t(0) identified-organization(4)
 etsi(0) cades(19122) attributes(1) 2 }
ClaimedSAMLAssertion ::= OCTET STRING 

As I told you, the standard is not complete on the SignerAttributeV2.signedAssertions part : 

> The definition of specific signedAssertions is outside of the scope of the present document. Any assertion encapsulated within this sequence shall be signed by third party. 

Unfortunately, I didn't find any complement in other ETSI/RFC/OASIS standards. I only found another reference in the ETSI TS 119 122-3. 

I'll wait for the feedbacks from ETSI and keep you informed. Maybe they can provide me some more details.

Regards,

Pierrick

**Pull request closed without merging**
