### PR TITLE
Extension for CommonDataLoader with Keystore (byte[] and not as path)

### PR DESCRIPTION
**Pull request by ankex**
Hi there,

this pull request contains:
- small fixes concerning the CR/LF inconsistent usages across all modules (XML files).
- extension for CommonDataLoader for KeyStore, evtl. required HostnameVerifier,  involved Protocols and Ciphers usages in combination with SSL connection factory.

Cheers,
Adrian.

### CODE REVIEW

**Comment by pvandenbroucke** [comment]
Hi Adrian,

Thanks for the pull request.

The changes on the CommonDataLoader have been partially retrieved. 
- I added setters for the new parameters (trustStrategy, supportedSSLProtocols, supportedSSLCipherSuites and hostnameVerifier)
- I didn't retrieve the binary keystore. It was not consistent with the truststore parameters. I added overridable methods getSSLKeyStore / getSSLTrustStore. I hope that suits you. Another solution could be to replace the filepaths with some KeyStoreCertificateSources (which takes binaries, file, path,...).

Could you explain me where is the problem with the CR/LF ? I retrieved your code and I didn't see other changes than the CommonDataLoader class. Does my git configuration not correct ? 

Thanks again for your help.

Regards,

Pierrick

**Comment by ankex** [comment]
Hi Pierrick,

we have done a fork for dss/develop some months ago. when we tried to update the fork with current develop branch then I got these conflicts. I suppose that either our fork was changed between the last to updates and some forgot to use the correct git settings and therefore the problem was only on our side , or someone else did this with the develop. I cann't say exactly from where it comes.

Thank's for adding the features. I'll check and eventually change my local extensions :)

Cheers,
Adrian.

**Comment by ankex** [comment]
Hi Pierrick,

this can be closed. 

Cheers,
Adrian.

**Comment by pvandenbroucke** [comment]
Hi Adrian,

Thanks for the feedback.

Regards,

Pierrick

**Pull request closed without merging**
