### PR TITLE
RSASSA-PSS

### PR DESCRIPTION
**Pull request by Bob88640**
Hello,
For RSASSA-PSS without Parameters
Identifiers:
http://www.w3.org/2007/05/xmldsig-more#sha3-224-rsa-MGF1
http://www.w3.org/2007/05/xmldsig-more#sha3-256-rsa-MGF1
http://www.w3.org/2007/05/xmldsig-more#sha3-384-rsa-MGF1
http://www.w3.org/2007/05/xmldsig-more#sha3-512-rsa-MGF1
http://www.w3.org/2007/05/xmldsig-more#md2-rsa-MGF1
http://www.w3.org/2007/05/xmldsig-more#md5-rsa-MGF1
http://www.w3.org/2007/05/xmldsig-more#sha1-rsa-MGF1
http://www.w3.org/2007/05/xmldsig-more#sha224-rsa-MGF1
http://www.w3.org/2007/05/xmldsig-more#sha256-rsa-MGF1
http://www.w3.org/2007/05/xmldsig-more#sha384-rsa-MGF1
http://www.w3.org/2007/05/xmldsig-more#sha512-rsa-MGF1
http://www.w3.org/2007/05/xmldsig-more#ripemd128-rsa-MGF1
http://www.w3.org/2007/05/xmldsig-more#ripemd160-rsa-MGF1
http://www.w3.org/2007/05/xmldsig-more#whirlpool-rsa-MGF1

from BC:
algorithms.put("SHA1WITHRSAANDMGF1", PKCSObjectIdentifiers.id_RSASSA_PSS);
algorithms.put("SHA224WITHRSAANDMGF1", PKCSObjectIdentifiers.id_RSASSA_PSS);
algorithms.put("SHA256WITHRSAANDMGF1", PKCSObjectIdentifiers.id_RSASSA_PSS);
algorithms.put("SHA384WITHRSAANDMGF1", PKCSObjectIdentifiers.id_RSASSA_PSS);
algorithms.put("SHA512WITHRSAANDMGF1", PKCSObjectIdentifiers.id_RSASSA_PSS);

You can add more identifiers to the framework but I'm interested in:
http://www.w3.org/2007/05/xmldsig-more#sha1-rsa-MGF1
http://www.w3.org/2007/05/xmldsig-more#sha256-rsa-MGF1

There is no common approach between XML & CMS, the same OID is used for different signature algorithms... It can create some issues.
Thanks,
Bob

### CODE REVIEW

**Comment by Bob88640** [comment]
Any news concerning this pull request?

**Comment by pvandenbroucke** [comment]
Hello Bob,

Thanks for your contribution. We added this support for a german TLSO and we are waiting his feedback. We will keep you informed soon.

Kind regards,

**Comment by Bob88640** [comment]
Hello Pierrick,
What do you mean by "We added this support for a german TLSO and we are waiting his feedback."?

**Comment by Bob88640** [comment]
Hello Pierrick,

Have you any idea when you will be able to integrate this pool request?
Thanks,
Bob

**Comment by naramski** [comment]
Can you please introduce this request as a feature request in JIRA. The new algorithm have to be supported in any environment, can you please add test material ?

**Pull request closed without merging**
