### PR TITLE
Fix for SunPKCS11 in Java 10 changes.

### PR DESCRIPTION
**Pull request by rastorehak**
SunPKCS11 does not longer supports constructor with InputStream. Instead it uses method configure( String ).
This fix invokes the method through reflection. In future Java version it won't be possible so the library must be build in Java 11.
Now it is possible to build it on Java 8 and run on 9 and 10.

### CODE REVIEW

**Comment by pvandenbroucke** [comment]
Hi,

Thanks for your contribution. 

Some changes have already be done for the next release to improve the Java 9+ support (https://ec.europa.eu/cefdigital/tracker/browse/DSS-1312). You can find the changes in the develop branch. This branch can be built with a JDK10.

Regards,

Pierrick

**Comment by rastorehak** [comment]
Exactly the same problem. Difference is in  multi release jar. This patch can be built on 8 and used on 9, 10.

**Comment by pvandenbroucke** [comment]
I'm afraid to don't understand. The [code](https://github.com/esig/dss/blob/develop/dss-token/src/main/java/eu/europa/esig/dss/token/Pkcs11SignatureToken.java#L220) in the develop branch detects the java version on the runtime.

Additionally, on compile time, we also explicitly add the required [modules](https://github.com/esig/dss/blob/develop/dss-token/pom.xml#L39).

**Comment by rastorehak** [comment]
Oh, sorry. I did not read the code carefully. I'v read "multi release jar" in comments and then I stop thinking. 
I am going to try this branch with our application.

**Pull request closed without merging**
