### PR TITLE
Error when report has more then one signature

### PR DESCRIPTION
**Pull request by miskoala**

### CODE REVIEW

**Comment by pvandenbroucke** [comment]
Hello Michał,

Do you have a reproductive case which cause the error ? 

Thanks in advance,

Pierrick

**Comment by miskoala** [comment]
Detailed report with more then one signature:
[_03dr.zip](https://github.com/esig/dss/files/1196626/_03dr.zip)

**Comment by miskoala** [comment]
Document with more then one signatures:
[more_then_one_signature.zip](https://github.com/esig/dss/files/1196647/more_then_one_signature.zip)

**Comment by miskoala** [comment]
When I try to validate document with more then one sitnature the exception is throw:

`Caused by: org.apache.fop.fo.ValidationException: Property ID "basicValidationData" (found on "fo:block") previously used; ID values must be unique within a document! (See fo:block, id=basicValidationData)
	at org.apache.fop.events.ValidationExceptionFactory.createException(ValidationExceptionFactory.java:38)
	at org.apache.fop.events.EventExceptionManager.throwException(EventExceptionManager.java:58)
	at org.apache.fop.events.DefaultEventBroadcaster$1.invoke(DefaultEventBroadcaster.java:173)
	at com.sun.proxy.$Proxy147.idNotUnique(Unknown Source)
	at org.apache.fop.fo.FObj.checkId(FObj.java:202)
	at org.apache.fop.fo.FObj.startOfNode(FObj.java:183)
	at org.apache.fop.fo.flow.Block.startOfNode(Block.java:144)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.startElement(FOTreeBuilder.java:337)
	at org.apache.fop.fo.FOTreeBuilder.startElement(FOTreeBuilder.java:179)
	at org.apache.xml.serializer.ToXMLSAXHandler.closeStartTag(ToXMLSAXHandler.java:206)
	at org.apache.xml.serializer.ToXMLSAXHandler.characters(ToXMLSAXHandler.java:524)
	at org.apache.xalan.templates.ElemTextLiteral.execute(ElemTextLiteral.java:218)
	... 112 more`

**Comment by pvandenbroucke** [comment]
Hello Michał,

I merged the fix on the XSLT in the develop branch + 5.1.x (for the next final release).

Thanks for your contribution.

Regards,

Pierrick

**Pull request closed without merging**
