### PR TITLE
Added signing at once method

### PR DESCRIPTION
**Pull request by Lonzak**
I added a method which does the signing within one method. It has less redundant method calls etc.

### CODE REVIEW

**Comment by pvandenbroucke** [comment]
Hello Lonzak,

Thanks for the proposal but I can't include it like this. I need unit tests which verify the conformance and different scenarios (B/T/LT/LTA).

As we already discussed, we would like to improve the PAdES module but we won't do it without any guaranteed,...

Regards,

Pierrick

**Comment by Lonzak** [comment]
Hi Pierrick,

I understand your reasons, although the "signDocumentAtOnce(...)" method is basically a merge of the three existing methods. So it would be quite strange if it wouldn't work with all the other variants of PAdES signatures.

As we discussed I would have liked to improve the module further however without a little help in the CMS part (the first block (~20 lines) in the signDocument() method) it is quite a challenge to do so...

**Comment by Lonzak** [comment]
Just a question: Is this feature now supported? (So I can throw out my method)?

**Comment by mkl-public** [comment]
Related: https://github.com/LibrePDF/OpenPDF/issues/296
Here the results of the repeated PDF manipulation were not byte-wise identical with OpenPDF.

**Pull request closed without merging**
