### PR TITLE
Validation of ASN.1 Evidence Record with omitted HashTree fails (DSS-3172)

### PR DESCRIPTION
**Pull request by fischerf**
Hi Aleksandr,

I saw your ticket regarding DSS-3172 today and wanted to write to you last week that this special case is not yet handled.

I have already implemented this for ASN.1 with a change to the [EvidenceRecordTimeStampSequenceVerifier in common](https://github.com/esig/dss/pull/172/commits/ae82860ac56af9c66a162e6e24c5e440f6f50ce0#diff-fa19a22d662d0727add776d90ff21d29f19ac551669ae05278668da8736907b4). This change would also work for XMLERS. It's not exactly elegant, but it was the easiest to implement.

You can take a look and see if you can use any of it.

When testing, there is an issue in [AbstractEvidenceRecordTestValidation L113-144](https://github.com/esig/dss/blob/ers-wip/dss-evidence-record-common/src/test/java/eu/europa/esig/dss/evidencerecord/common/validation/AbstractEvidenceRecordTestValidation.java#L113-L116), but I don't know exactly what is being tested here, so I left it open for you :).

best regards
Florian

### CODE REVIEW

**Comment by bsanchezb** [comment]
Hi Florian,

I have indeed already began to work on this issue as well. In fact, your solution seems very similar to mine in logic, as I also add a "virtual" hash tree, before starting a time-stamp validation.

I see that you added a few unit tests as well. I will check if all these test cases pass with my solution and will push the code after.

Thank you for your assistance!

Best regards,
Aleksandr.

**Comment by SiENcE** [comment]
Hi Aleksandr,

Then it's better to take your implementation and just apply the test cases and the new function  [ASN1EvidenceRecordTimeStampSequenceVerifier.java](https://github.com/esig/dss/pull/172/commits/ae82860ac56af9c66a162e6e24c5e440f6f50ce0#diff-b195bd6c6c27b6b714e1c24b0a2f3ad0b8d28bca8da4a167630449a0f002a91e)

Have a nice weekend
Florian

**Comment by bsanchezb** [comment]
Hi Florian,

I have updated https://github.com/esig/dss/tree/ers-wip branch, including your changes and unit tests from this PR.
The unit tests still fail due to a difference in _ArchiveTimeStampChain_ renewal between RFC 4998 and RFC 6283.

From my understanding, RFC 4998 requires a first Archive Time Stamp within an ArchiveTimeStampChain to contain hashes corresponding to all documents from the initial data group, where each hash is built on a concatenation of a document hash and a previous ArchiveTimeStampChain's hash.
While RFC 6283 requires a first Archive Time Stamp within an ArchiveTimeStampChain to have original document hashes and previous ArchiveTimeStampChain's hash separately.

As my current code is more RFC 6283 centric, it creates an additional _EVIDENCE_RECORD_ARCHIVE_TIME_STAMP_SEQUENCE_ Digest Matcher in addition to the created _EVIDENCE_RECORD_ARCHIVE_OBJECT_ digest matchers from data object hashes. However, it seems like in ASN.1 implementation, this additional digest matcher is redundant, as time-stamp hashes are built on combination of document hashes and archive-time-stamp-sequence's hash.

Thus, taking into account written above, it seems to me that the method _computePrecedingTimeStampSequenceHash()_ called in line [EvidenceRecordTimeStampSequenceVerifier.java#L96](https://github.com/esig/dss/blob/ers-wip/dss-evidence-record-common/src/main/java/eu/europa/esig/dss/evidencerecord/common/validation/EvidenceRecordTimeStampSequenceVerifier.java#L96) should be modified to return a list/collection of _DSSMessageDigest_'s one for each original document to allow valid processing of RFC 4998 evidence records (while it will always return a single value for RFC 6283 ER). Additionally, the method [ validateArchiveTimeStampSequenceDigest(...)](https://github.com/esig/dss/blob/ers-wip/dss-evidence-record-common/src/main/java/eu/europa/esig/dss/evidencerecord/common/validation/EvidenceRecordTimeStampSequenceVerifier.java#L125C52-L125C90) will need to be adapted to process the new parameter.

What is your opinion on this? Could you please adapt the implementation to handle the ASN.1 format correctly (as you definitely know it better than me)?

Best regards,
Aleksandr.

**Comment by fischerf** [comment]
Hi Aleksandr,

Please check my modifications.

"validateArchiveTimeStampSequenceDigest" (https://github.com/fujitsu-dsps-org/dss/blob/ers-wip/dss-evidence-record-common/src/main/java/eu/europa/esig/dss/evidencerecord/common/validation/EvidenceRecordTimeStampSequenceVerifier.java#L126-L127) has to deal with a list of lastTimeStampSequenceHashes.

The current ASN.1 Testcases are all positive. All test cases must be run through without any special test overrides.

best regards,
Florian

**Comment by bsanchezb** [comment]
Hi Florian,

I merged the PR to https://github.com/esig/dss/tree/ers-wip branch, with minor modifications. Could you please take a look whether everything looks correct?

Best regards,
Aleksandr

**Pull request merged**
