### PR TITLE
Upgrade PDFBox to 2.0.3

### PR DESCRIPTION
**Pull request by backslash47**
Upgraded to PDFBox 2.0.3.

Needs to disable two tests in GetOriginalDocumentTest because PDFBox has stricter parsing and "original document" from signature is not a valid PDF document (not even in PDFBox 1.8, but 1.8 has lenient parsing). Will be solved if https://issues.apache.org/jira/browse/PDFBOX-3545 fixed.

### CODE REVIEW

**Comment by Lonzak** [comment]
There is already a bug for this:
https://esig-dss.atlassian.net/browse/DSS-969

**Comment by pvandenbroucke** [comment]
Hello Backslash47 and Lonzak,

Thanks for your contribution. We will need more time to integrate it. There's some more stuff to do. With the latest major release of PDFBox, we shouldn't need to create new temporary files. 

Kind regards,

Pierrick

**Comment by backslash47** [comment]
Hello Pierrick,
Thank you for the information. I am looking forward to the version of dss with pdfbox 2. I am sure there is much to do, all I have done, was to make all the tests to pass. Hope somebody can make the changes you described.
My motivation to upgrade was using apache Tika for document parsing and they moved to pdfbox 2 and it colides with pdfbox 1.8 needed for dss. 
Do you have a timeframe in we could expect an official version of dss with pdfbox 2?
Best regards,
Matus
Dňa 28.10.2016 10:56 používateľ Pierrick Vandenbroucke <notifications@github.com> napísal:Hello Backslash47 and Lonzak,

Thanks for your contribution. We will need more time to integrate it. There's some more stuff to do. With the latest major release of PDFBox, we shouldn't need to create new temporary files. 

Kind regards,

Pierrick

**Comment by pvandenbroucke** [comment]
Hello Backslash47,

The upgrade of the PDFBox version is in the roadmap. Currently, we have other priorities for next months (Pivot LOTL, Support of EN 119-172, ASiC Plugtests,...).

I also found this [fork](https://github.com/srebrinb/dss-pades-pdfbox2/commits/try-pades-pdfbox2) but I didn't test it yet (without temp files).

Kind regards,

Pierrick

**Comment by Lonzak** [comment]
No this one uses an older version of DSS and PDFBox, still has lots of bugs inside... Our versions is better and more up-to-date

**Comment by backslash47** [comment]
Thanks for pointing out the fork with removed temp files. I will give it a look during next week. 
Regards,
Matus
Dňa 28.10.2016 11:58 AM používateľ Pierrick Vandenbroucke <notifications@github.com> napísal:Hello Backslash47,

The upgrade of the PDFBox version is in the roadmap. Currently, we have other priorities for next months (Pivot LOTL, Support of EN 119-172, ASiC Plugtests,...).

I also found this fork but I didn't test it yet (without temp files).

Kind regards,

Pierrick

**Comment by backslash47** [comment]
Hello.
Please have a look at the changes. I took the inspiration from mentioned fork and gone a little further. 
Best regards,
Matus
Dňa 28.10.2016 17:06 používateľ Matúš Zamborský <zamborsky@inqool.cz> napísal:Thanks for pointing out the fork with removed temp files. I will give it a look during next week. 
Regards,
Matus
Dňa 28.10.2016 11:58 AM používateľ Pierrick Vandenbroucke <notifications@github.com> napísal:Hello Backslash47,

The upgrade of the PDFBox version is in the roadmap. Currently, we have other priorities for next months (Pivot LOTL, Support of EN 119-172, ASiC Plugtests,...).

I also found this fork but I didn't test it yet (without temp files).

Kind regards,

Pierrick

**Comment by pvandenbroucke** [comment]
Hello Matus,

Sorry for delay, I was busy with the ASiC Plugtests. I merged your contribution in the develop branch.

I still have to fix the getOriginalDocument.

Thanks for your contribution.

Kind regards,

Pierrick

**Pull request closed without merging**
