### PR TITLE
P.5.3.2

### PR DESCRIPTION
**Pull request by 2at2**
Added encapsulated certificates as certificates to veryfing
Added QualifyingPropertiesReference resolver

### CODE REVIEW

**Comment by modax** [comment]
Hi, devs! anything could be done to include this PR or functionality? Apparently there are some frameworks which do not add `ds:KeyInfo/ds:X509Data` but certs are only `QualifyingPropertiesReference` ... How insane is that...

**Comment by pvandenbroucke** [comment]
Hello,

Anyway, we are curious to get some samples with your tag usage.

The specification says : 

```
<xsd:complexType name="QualifyingPropertiesReferenceType">
  <xsd:sequence>
    <xsd:element name="Transforms" type="ds:TransformsType" minOccurs="0"/>
  </xsd:sequence>
  <xsd:attribute name="URI" type="xsd:anyURI" use="required"/>
  <xsd:attribute name="Id" type="xsd:ID" use="optional"/>
</xsd:complexType>
```

How do you add your certificates in this case ? Another tag anywhere in the XML ?

If you can attach some examples of signed files with the other tool, that could help us.

Thanks in advance,

Regards,

Pierrick

**Comment by modax** [comment]
hi @pvandenbroucke,

I can't provide a real example in this case but I will anonimize and indent it for clarify.

So the signed document:

```
<?xml version="1.0" encoding="UTF-8"?>
<Root>
  <Document>goes here</Document>
  <Signature xmlns="http://www.w3.org/2000/09/xmldsig#" Id="SIG_1234">
    <SignedInfo>
      <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
      <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
      <Reference URI="">
        <Transforms>
          <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
        </Transforms>
        <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
        <DigestValue>[some-base64]</DigestValue>
      </Reference>
      <Reference URI="#SIG_PROP_5678" Type="http://uri.etsi.org/01903/v1.1.1#SignedProperties">
        <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
        <DigestValue>[some-base64]</DigestValue>
      </Reference>
    </SignedInfo>
    <SignatureValue>[some-base64]</SignatureValue>
    <ds:Object xmlns="http://uri.etsi.org/01903/v1.1.1#" xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
      <QualifyingPropertiesReference URI="http://some.where/cert/id-here"/>
      <QualifyingPropertiesReference URI="http://some.where/crl/id-here"/>
      <QualifyingProperties Target="#SIG_1234">
        <SignedProperties Id="SIG_PROP_5678">
          <SignedSignatureProperties>
            <SigningTime>2018-01-01T13:40:00+01:00</SigningTime>
            <SigningCertificate>
              <Cert>
                <CertDigest>
                  <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
                  <DigestValue>sdNcEL4nah51QkSiq+Cd8pckxu4=</DigestValue>
                </CertDigest>
                <IssuerSerial>
                  <ds:X509IssuerName>CN=INTER CA</ds:X509IssuerName>
                  <ds:X509SerialNumber>222222</ds:X509SerialNumber>
                </IssuerSerial>
              </Cert>
            </SigningCertificate>
            <SignaturePolicyIdentifier>
              <SignaturePolicyImplied/>
            </SignaturePolicyIdentifier>
          </SignedSignatureProperties>
        </SignedProperties>
        <UnsignedProperties>
          <UnsignedSignatureProperties>
            <SignatureTimeStamp>
              <HashDataInfo uri="#SIG_1234">
                <Transforms>
                  <ds:Transform xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Algorithm="http://www.w3.org/TR/1999/REC-xpath-19991116">
                    <ds:XPath xmlns:dsig="http://www.w3.org/2000/09/xmldsig#">ancestor-or-self::dsig:SignatureValue</ds:XPath>
                  </ds:Transform>
                </Transforms>
              </HashDataInfo>
              <EncapsulatedTimeStamp Id="TSP_9012">[some-base64]</EncapsulatedTimeStamp>
            </SignatureTimeStamp>
          </UnsignedSignatureProperties>
        </UnsignedProperties>
      </QualifyingProperties>
    </ds:Object>
  </Signature>
</EDoc>
```

http://some.where/cert/id-here

```
<?xml version="1.0" encoding="UTF-8"?>
<QualifyingProperties xmlns="http://uri.etsi.org/01903/v1.1.1#" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Target="#URL_CERT_3456">
  <UnsignedProperties>
    <UnsignedSignatureProperties>
      <CompleteCertificateRefs Id="CCR">
        <CertRefs>
          <Cert>
            <CertDigest>
              <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
              <DigestValue>fnqpj+xeX+cEkho2Mys5TVIb4jg=</DigestValue>
            </CertDigest>
            <IssuerSerial>
              <ds:X509IssuerName>CN=INTER CA</ds:X509IssuerName>
              <ds:X509SerialNumber>222222</ds:X509SerialNumber>
            </IssuerSerial>
          </Cert>
          <Cert>
            <CertDigest>
              <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
              <DigestValue>lXS2sDQdzLhy4BttFnTIiB/eFSI=</DigestValue>
            </CertDigest>
            <IssuerSerial>
              <ds:X509IssuerName>CN=ROOT CA</ds:X509IssuerName>
              <ds:X509SerialNumber>111111</ds:X509SerialNumber>
            </IssuerSerial>
          </Cert>
        </CertRefs>
      </CompleteCertificateRefs>
      <CertificateValues Id="CV">
        <EncapsulatedX509Certificate Id="CV_222222">[base64 of SIGNER certificate]</EncapsulatedX509Certificate>
        <EncapsulatedX509Certificate Id="CV_111111">[base64 of INTER CA certificate]</EncapsulatedX509Certificate>
        <EncapsulatedX509Certificate Id="CV_000000">[base64 of ROOT CA cetificate]</EncapsulatedX509Certificate>
      </CertificateValues>
    </UnsignedSignatureProperties>
  </UnsignedProperties>
</QualifyingProperties>
```

http://some.where/crl/id-here

```
<?xml version="1.0" encoding="UTF-8"?>
<QualifyingProperties xmlns="http://uri.etsi.org/01903/v1.1.1#" Target="#URL_CRL_7890">
  <UnsignedProperties>
    <UnsignedSignatureProperties>
      <CompleteRevocationRefs Id="CRR">
        <CRLRefs>
          <CRLRef>
            <DigestAlgAndValue>
              <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
              <DigestValue>w8saOeaeP8OWIpfpSQROGOlb4uQ=</DigestValue>
            </DigestAlgAndValue>
            <CRLIdentifier>
              <Issuer>CN=INTER CA</Issuer>
              <IssueTime>2017-02-10T20:00:00Z</IssueTime>
            </CRLIdentifier>
          </CRLRef>
          <CRLRef>
            <DigestAlgAndValue>
              <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
              <DigestValue>Dx15MNhNIBnTR/9oRDS5Q2Wyyng=</DigestValue>
            </DigestAlgAndValue>
            <CRLIdentifier>
              <Issuer>CN=ROOT CA</Issuer>
              <IssueTime>2016-05-05T12:00:00Z</IssueTime>
            </CRLIdentifier>
          </CRLRef>
        </CRLRefs>
      </CompleteRevocationRefs>
      <RevocationValues Id="RV">
        <CRLValues>
          <EncapsulatedCRLValue Id="CRL_2222">[base64 of INTER CA crl]</EncapsulatedCRLValue>
          <EncapsulatedCRLValue Id="CRL_1111">[base64 of ROOT CA crl]</EncapsulatedCRLValue>
        </CRLValues>
      </RevocationValues>
    </UnsignedSignatureProperties>
  </UnsignedProperties>
</QualifyingProperties>
```

As far as I can tell, `QualifyingProperties` at http://some.where/cert/id-here and http://some.where/crl/id-here have no strict relation to the signature itself. `id-here` is a hash/serial number of either cert or crl so they do not need to be shipped with each signature embedded and can later be retrieved via URL. I'm not a big fan of this but apparantly other people do it for some reason (to save on storage?)

What I see DSS should do is to follow that URI and "expand" retrieved contents as if `QualifyingProperties` block was just there in the document itself. That's it. Not sure about transforms part.

What's more, I don't think it is particularly important for DSS to be able to create signatures with these references, it should only be able to validate them.

**Comment by bsanchezb** [comment]
We will continue in the created ticket https://ec.europa.eu/cefdigital/tracker/browse/DSS-1840 .

Best regards,
Aleksandr.

**Pull request closed without merging**
