### PR TITLE
Implementation of https (with mutual authentication) in CommonsDataLoader.

### PR DESCRIPTION
**Pull request by lodermatt**
This modification adds the possibility to use https whith a Time Stamp
Authority. It adds keystore and truststore managers and repairs some
bugs (see https://esig-dss.atlassian.net/browse/DSS-850)

### CODE REVIEW

**Comment by naramski** [comment]
Thanks for you work. Can you please try to do the same on the "develop" branch next time ? We will integrate this one ourselves. Many thanks !

**Comment by pvandenbroucke** [comment]
Hello lodermatt,

Thanks for your pull request. I just tried it but the proposed code doesn't compile (constructors don't match,...). Could you have a look ?

Thanks in advance,

Kind regards,

Pierrick

**Comment by lodermatt** [comment]
You're right! My previous modifications were not correct, sorry for that. I pushed the good classes (eclipse ruined the tabulations, sorry)

**Comment by naramski** [comment]
Merged in develop

**Pull request closed without merging**
