### PR TITLE
Develop dataloader fix

### PR DESCRIPTION
**Pull request by fischerf**
Here is a small fix for the lastest changes of Dataloader. Otherwise you get an runtime problem.

### CODE REVIEW

**Comment by pvandenbroucke** [comment]
Hello Florian,

Which kind of problem do you meet ? The implementation of the DataLoader can be injected in the FileCacheDataLoader with the setter or the constructor. The default behavior will use a new CommonDataLoader.

Kind regards,

Pierrick

**Comment by SiENcE** [comment]
Hi Pierrick,

Oh sorry. Yes i meant the new CommonDataLoader. There is a problem when starting up, the bean cannot bind the proxyconfiguration. Sorry, i've only smartphone available rightnow.

Cheers

**Comment by fischerf** [comment]
Hi Pierrick,

Oh sorry. Yes i meant the new CommonDataLoader. There is a problem when starting up, the bean cannot bind the proxyconfiguration. Sorry, i've only smartphone available rightnow.

Cheers

**Comment by pvandenbroucke** [comment]
Hi Florian,

IMO, the FileCacheDataLoader should be considered as a [Proxy pattern](https://en.wikipedia.org/wiki/Proxy_pattern). We may remove the default/empty constructor to avoid confusion,...

Kind regards,

Pierrick

**Comment by pvandenbroucke** [comment]
Hello again,

I removed the default behavior in this [commit](https://github.com/esig/dss/commit/c0e66f0872e94bb607d8c5ff1b6f72f869c04326).

Kind regards,

Pierrick

**Comment by fischerf** [comment]
Not needed anymore. So i close this.

**Pull request closed without merging**
