### PR TITLE
Start the work to support ICP Brazil explicit signature policies.

### PR DESCRIPTION
**Pull request by davydsantos**
Start the work to support ICP Brazil explicit signature policies.
- Added signature levels and formats
- Added Filter + subfilter + sigPolicy OID check
- Added a test pdf and a test case with a signature and a fake certificate (still pending definition on trust-anchor from signature-policy, for now it relies on a user-defined trust using CommonTrustedCertificateSource)

### CODE REVIEW

**Comment by pvandenbroucke** [comment]
Hello Davyd,

Do you have any link with specifications,... ? I only found these [slides](https://prezi.com/9tfaugh9rppr/pades/) and they still use the ETSI.CAdES.detached and ETSI.RFC3161 subfilters.

Regards,

Pierrick

**Comment by davydsantos** [comment]
So, the documents are [here](http://www.iti.gov.br/legislacao/143-icp-brasil/legislacao/790-doc-icp) and the specific document talking about signature policy is the [DOC ICP 15.03](http://www.iti.gov.br/images/twiki/URL/pub/Certificacao/DocIcp/docs13082012/DOC-ICP-15.03_-_Versao_7.3_REQ_DAS_POL_DE_ASSIN__DIG_NA_ICP-BRASIL.pdf) and this is the ASN.1 set:
- [AD_RB](http://politicas.icpbrasil.gov.br/PA_PAdES_AD_RB_v1_0.der): relates to PAdES-B
- [AD_RT](http://politicas.icpbrasil.gov.br/PA_PAdES_AD_RT_v1_0.der): relates to PAdES-T
- [AD_RC](http://politicas.icpbrasil.gov.br/PA_PAdES_AD_RC_v1_1.der): relates to PAdES-LT
- [AD_RA](http://politicas.icpbrasil.gov.br/PA_PAdES_AD_RA_v1_1.der): relates to PAdES-LTA

*it's all in pt-BR

**Comment by davydsantos** [comment]
Will loop back on adding this in the future.

**Comment by direisc** [comment]
@davydsantos your code with ICP Brazil suport works? You can help me?
Sorry every one but i talk in portuguese now...

estou em apuros tentando usar as politicas do ICP porem não consigo uma solução elegante para o mesmo! Você poderia ajudar?

**Comment by davydsantos** [comment]
@direisc, I don't know if I understand what is your problem but if you want to validate a signature against ICP BR policies, you can use https://validator.docusign.com. If you have any feedback related to the tool, you can email it to validator-feedback@docusign.com

**Comment by direisc** [comment]
Details os sign file:
` Assinado por: DIEGO REIS CARVALHO:34189766895 
Status: 
Indeterminada
Verificado de acordo com regulamentação ICP Brasil AD-RB

    Não foi possível validar a assinatura porque a política de assinatura não coincide com o conteúdo da assinatura. Os motivos estão detalhados abaixo:
    Entradas de dicionário PDF ausentes/inválidas

Nome: DIEGO REIS CARVALHO:34189766895
E-mail: direisc@gmail.com
Data/hora da assinatura: 2018-06-06 13:31:40 -0300
Detalhes
Caminho do certificado:

    Autoridade Certificadora Raiz Brasileira v2
        AC Secretaria da Receita Federal do Brasil v3
            AC Imprensa Oficial SP RFB G4
                DIEGO REIS CARVALHO:34189766895

Validade: 2017-08-02 15:27:42 -0300 para 2020-08-02 15:27:42 -0300
Ponto de confiança: Autoridade Certificadora Raiz Brasileira v2
Nível da assinatura: PAdES-BASELINE-B
Número de série: 01 1E 74 B8 6F 33 CC CD ED
Política de assinatura:  2.16.76.1.7.1.11.1   URL:  http://politicas.icpbrasil.gov.br/PA_PAdES_AD_RB_v1_0.der
Algoritmo da assinatura: SHA256 RSA
Algoritmo de hash da assinatura: SHA256 `

Why Signature Policy don't valid using ICP-Brasil policy? OID is incomplete or I need concat urn:oid:2.16.76.1.7.1.11.1

**Pull request closed without merging**
