### PR TITLE
Upgrade to PDFBox 2.0.3 (including temp file removal)

### PR DESCRIPTION
**Pull request by Lonzak**
Changes speak for themselves, if you have questions don't hesitate to ask

### CODE REVIEW

**Comment by Lonzak** [comment]
Did an upgrade to PDFBox 2.0.3

**Comment by pvandenbroucke** [comment]
Hello Lonzak,

Thanks for your contribution. I merged your several bug fixes in the develop branch.

About the upgrade of PDFBox, there's some more stuff to do. With the latest major release of PDFBox, we shouldn't need to create new temporary files. We will need more time to integrate it.

Kind regards,

Pierrick

**Comment by Lonzak** [comment]
Agreed - I saw that, too and thought that it can be improved (But didn't have the time yet)

**Comment by Lonzak** [comment]
Removed the temp files and lots of other memory copies of the PDF.

**Comment by Lonzak** [comment]
On last remark on this issue:
The signing of the document is done twice: Once to retrieve the messageDigest and then in a second step the actual signing is done. I didn't have the time to fully dig into the matter however it is possible to do that in one step. PDFBox offers something called "external signing" which provides a mechanism exectly for that. Have a look at the `saveIncrementalForExternalSigning()` method (and its javadoc). There is also an example in the CreateVisibleSignature.java (part of PDFBox examples)

**Comment by pirardn** [comment]
Dears,

This message is to remind you about the interest expression for the DSS Hackathon organised by EU-FOSSA 2 project team over the weekend of 5th- 6th October 2019.

The Hackathon, held in Brussels @ Silversquare Triomphe<https://urldefense.proofpoint.com/v2/url?u=https-3A__silversquare.eu_location_triomphe_&d=DwMFAw&c=8NwulVB6ucrjuSGiwL_ckQ&r=kX0ImnrSXE0VzRJXQpnXEyKiVqFYysekaPsY_--UkZo&m=986aPMkXj1GPnBup-RLqA1UNuUiZE1h02iRg1Hq5wl4&s=BRkZdl2ZYcoSKXtDM_6b1TwlfYCI2X7sxsNRf1o7QL0&e=> , showcases a selected open source community, and provides them a wonderful opportunity to get together and meet face to face. Travel and accommodation are provided to those from out of town.


The Digital Signature Software (DSS) is an open-source library that ensures your e-signatures and e-seals are created and verified in line with European legislation and standards.

If interested, please access the registration link below to express your interest to attend: https://eufossahackathon.bemyapp.com/ by 4th of September COB.

In case you know some other people interested in the proposed topic, do not hesitate to share the message or the interest registration link.

The agenda is not yet defined but here are some work items that could be addressed
-Performance
-PDF
-Security (Xml, PDF, Webapp)
-Java 12
-JavaFX for the Standalone version

If you have any question, don’t hesitate to send an email to Ana.RAMOS@ext.ec.europa.eu<mailto:Ana.RAMOS@ext.ec.europa.eu> from the EU-FOSSA 2 Project or to myself.

Best regards,


-----------------------------------------------------------------
Adrian CROITORU

[cid:image001.gif@01D5627A.9AC60AE0]
European Commission
DG DIGIT
Trans-European Services (D3)
Digital Identity and Signature Services (DISS)
12, rue Guillaume Kroll - DRB A2/053
L-1882 Luxembourg

E-mail: adrian.croitoru@ec.europa.eu<mailto:adrian.croitoru@ec.europa.eu>
      P      Help save paper - do you need to print this email?

**Pull request closed without merging**
