### PR TITLE
Set TSP request Content-Type to application/timestamp-query

### PR DESCRIPTION
**Pull request by metsma**
Signed-off-by: Raul Metsma <raul@metsma.ee>

### CODE REVIEW

**Comment by pvandenbroucke** [comment]
Hello Raul,

You can find this [class](https://github.com/esig/dss/blob/master/dss-service/src/main/java/eu/europa/esig/dss/client/http/commons/TimestampDataLoader.java) in the source code which has the specific content-type.

Kind regards,

Pierrick

**Comment by metsma** [comment]
I am using REST API and was hoping to use out of the box war, with minimal changes to repackage war with altering WEB-INF/classes/spring/applicationContext-core.xml tspServer default server URL.
<property name="tspServer" value="http://tsa.provider.ee"/>

The problem is that target server requires Content-Type and default war does not send it.

**Comment by pvandenbroucke** [comment]
Ok, in this case, you can create your bean like this : 

`<bean id="tspDataLoader" class="eu.europa.esig.dss.client.http.commons.TimestampDataLoader">
		<property name="proxyPreferenceManager" ref="proxyPreferenceManager"/>
</bean>`

and replace the ref of this [line](https://github.com/esig/dss/blob/master/dss-demo-webapp/src/main/resources/spring/applicationContext-core.xml#L46) with tspDataLoader.

I will change the config in the next release.

Kind regards,

Pierrick

**Comment by metsma** [comment]
Thank you, this solution works

**Pull request closed without merging**
