### PR TITLE
rotate support for visual signature

### PR DESCRIPTION
**Pull request by zsoltii**
We was get 2 pdf-s: "sun.pdf" and "sun90.pdf". These pdf-s seem similar. It isn't true, because the a sun.pdf is a normal pdf, the sun90.pdf is a rotated pdf and without the rotation support the visual signature place and rotation is difference after signing the pdf-s.

Rotataion support has 5 option:

- NONE: like the original method without rotation support
- AUTOMATIC: automatically does the rotation
- ROTATE_90: force 90° rotation
- ROTATE_180: force 180° rotation
- ROTATE_270: force 270° rotation

### CODE REVIEW

**Comment by pvandenbroucke** [comment]
Hello Zsolt,

Sorry for the delay, I was out of office these last days. Thanks for your proposal, I like the idea.

I had a a look to your PR, but I don't understand everything. When I try the manual test with the different parameters, I don't get the expected result. Eg : NONE, the generated visible signature has a 90° rotation. Did I miss anything? 

Regards,

Pierrick

**Comment by zsoltii** [comment]
Paste this code to the PAdESVisibleSignaturePositionTest.java file.
I hope it helping you.
I was attached the result pdf files.
[check_90_automatic.pdf](https://github.com/esig/dss/files/1187830/check_90_automatic.pdf)
[check_90_none.pdf](https://github.com/esig/dss/files/1187828/check_90_none.pdf)
[check_normal_automatic.pdf](https://github.com/esig/dss/files/1187829/check_normal_automatic.pdf)
[check_normal_none.pdf](https://github.com/esig/dss/files/1187831/check_normal_none.pdf)

```java
    @Test
    @Ignore("for pull request #71")
    public void rotatePullRequest71Test() throws Exception {
        Logger logger = LoggerFactory.getLogger(getClass());
        /**
         * minolta scanner normal(not rotated) pdf and rotation none.
         *
         * You can check the pdf rotation by this code:
         * PDDocument inputPDF = PDDocument.load(getClass().getResourceAsStream("/visualSignature/sun.pdf"));
         * System.out.println("rotation: " + inputPDF.getPage(0).getRotation());
         *
         * result in pdf viewer: signature is top left corner and the sign image line is parallel with the sun eyes line
         *
         * comment: this is the original working
         */
        PDDocument inputPDF = PDDocument.load(getClass().getResourceAsStream("/visualSignature/sun.pdf"));
        logger.info("rotation sun.pdf: " + inputPDF.getPage(0).getRotation());

        SignatureImageParameters signatureImageParameters = createSignatureImageParameters();

        signatureImageParameters.setRotation(SignatureImageParameters.VisualSignatureRotation.NONE);
        DSSDocument document = sign(signablePdfs.get("minoltaScan"));
        File checkPdfFile = new File("target/pdf/check_normal_none.pdf");
        checkPdfFile.getParentFile().mkdirs();
        IOUtils.copy(document.openStream(), new FileOutputStream(checkPdfFile));

        /**
         * minolta scanner rotated pdf and rotation none (in pdf view the rotated and normal pdf seem equal)
         * you can check the pdf rotation by this code:
         * PDDocument inputPDF = PDDocument.load(getClass().getResourceAsStream("/visualSignature/sun_90.pdf"));
         * System.out.println("rotation: " + inputPDF.getPage(0).getRotation());
         *
         * result in pdf viewer: signature is top right corner and the sign image line is perpendicular with the sun eyes line
         *
         * comment: this is the original working
         */
        inputPDF = PDDocument.load(getClass().getResourceAsStream("/visualSignature/sun_90.pdf"));
        logger.info("rotation sun_90.pdf: " + inputPDF.getPage(0).getRotation());

        signatureImageParameters = createSignatureImageParameters();

        signatureImageParameters.setRotation(SignatureImageParameters.VisualSignatureRotation.NONE);
        document = sign(signablePdfs.get("minoltaScan90"));
        checkPdfFile = new File("target/pdf/check_90_none.pdf");
        checkPdfFile.getParentFile().mkdirs();
        IOUtils.copy(document.openStream(), new FileOutputStream(checkPdfFile));

        /**
         * minolta scanner rotated pdf and rotation automatic (in pdf view the rotated and normal pdf seem equal)
         *
         * result in pdf viewer: signature is top left corner and the sign image line is parallel with the sun eyes line,
         * it will be same as with sun.pdf (not rotated) and rotation none
         */
        signatureImageParameters = createSignatureImageParameters();

        signatureImageParameters.setRotation(SignatureImageParameters.VisualSignatureRotation.AUTOMATIC);
        document = sign(signablePdfs.get("minoltaScan90"));
        checkPdfFile = new File("target/pdf/check_90_automatic.pdf");
        checkPdfFile.getParentFile().mkdirs();
        IOUtils.copy(document.openStream(), new FileOutputStream(checkPdfFile));

        /**
         * minolta scanner normal(not rotated) pdf and rotation none.
         *
         * result in pdf viewer: signature is top left corner and the sign image line is parallel with the sun eyes line,
         * it will be same as with sun.pdf (not rotated) and rotation none
         */
        signatureImageParameters = createSignatureImageParameters();

        signatureImageParameters.setRotation(SignatureImageParameters.VisualSignatureRotation.AUTOMATIC);
        document = sign(signablePdfs.get("minoltaScan"));
        checkPdfFile = new File("target/pdf/check_normal_automatic.pdf");
        checkPdfFile.getParentFile().mkdirs();
        IOUtils.copy(document.openStream(), new FileOutputStream(checkPdfFile));
    }
```

**Comment by pvandenbroucke** [comment]
Hello Zsolt,

Thanks for this additional information. You are covering the case of /Rotate (in the PDF binaries). I didn't know this feature in the PDF (Adobe displays both in the same way). So, in some cases, you can have a double rotation.

I will check tomorrow to merge your pull request.

Thanks again for your feedback.

Regards,

Pierrick

**Comment by pvandenbroucke** [comment]
Hello Zsolt,

I merged your proposal in the develop branch. Great thanks for your contribution. 

Regards,

Pierrick

**Pull request merged**
