### PR TITLE
Add support for ServiceSupplyPoints - PL TSL store in this place CRL's urls

### PR DESCRIPTION
**Pull request by miskoala**
Add support for ServiceSupplyPoints - PL TSL store in this place CRL's urls

### CODE REVIEW

**Comment by pvandenbroucke** [comment]
Hello Michał,

Thanks for your proposal. 

I created the following [Jira ](https://ec.europa.eu/cefdigital/tracker/browse/DSS-1228) to add this support.

Do you have any signature sample which require this information (signing certificate without the crl distribution point and a trust anchor with the ServiceSupplyPoints) ? 

Regards,

Pierrick

**Comment by pvandenbroucke** [comment]
Hello again,

I merged and continued to add the support of the ServiceSupplyPoints. 

When DSS needs to request for revocation data, it will firstly search CRL/OCSP url(s) in the certificate. If no information is found, DSS will try to find the trust anchor and retrieves the ServiceSupplyPoints.

I also added the urls in the diagnostic data.

I have no material to test this feature. Any feedback is welcome.

Regards,

Pierrick

**Comment by miskoala** [comment]
There are samples:
[signatures.zip](https://github.com/esig/dss/files/1189541/signatures.zip)

**Comment by pvandenbroucke** [comment]
Thanks for these signatures. 

It works well with the your samples. I did a small change to get the warning on the revocation data. The CRL/OCSP url should be present in the certificate (910/EU/2014 Annex I point i).

You can see the validation result in the [Jira ](https://ec.europa.eu/cefdigital/tracker/browse/DSS-1228).

Regards,

Pierrick

**Pull request merged**
