### PR TITLE
DSS-3242: Sign multiple times Xades check

### PR DESCRIPTION
**Pull request by Pierre-Lemaigre**
This PR refines the xades signature check to allow for multiple
signatures with enveloped transforms when they are not parallel.

For more infos, see ticket [DSS-3242](https://ec.europa.eu/digital-building-blocks/tracker/browse/DSS-3242)

### CODE REVIEW

**Comment by bsanchezb** [comment]
Hi Pierre,

I did a quick look on the PR. I'm not sure if the correct direction has been taken. What you are trying to ensure (correct me if I'm wrong) is whether the new signature will not be added within the same element as existing signatures (or within corresponding parent).
But what is more important, is not the location of the existing signatures, but the covered content. For instance, if the first signature is created with a _<ds:Reference URI="">_ instead, with no location changed, the newly added signature will break it wherever it is being added to. At the same time, both signatures may be legally added within the same element, provided they do cover different content (then enveloped-signature-transform makes little sense, but it still possible, technically speaking).

In pseudo-code you need something like:
```
Node parentSignatureNode = getParentNodeOfSignature();
for (Node signatureNode : existingSignatures) {
    List<Node> coveredContent = getCoveredContent(signatureNode);
    if (containsNode(coveredContent, parentSignatureNode) {
          continue;
    }
    assertDoesNotContainEnvelopedTransform(signatureNode);
} 
```
The method _getCoveredContent(signatureNode)_ should return a list of Node's actually covered by the signature, by looping over signature's _ds:Reference_ elements, and de-referencing the content by URI (defined either with an empty URI "", or an Id element anchor "#XX"). You may avoid additional handling of xpointer and/or Transforms for simplicity (and to avoid additional processing).
Method _containsNode(coveredContent, parentSignatureNode)_, should evaluate that _parentSignatureNode_ is not part of the _coveredContent_ Node's or their children recursively.

Let me know what you think.

KR,
Aleksandr.

**Comment by Pierre-Lemaigre** [comment]
Hi Aleksandr,
What a mistake I made, you are totally right. 

But for the second part i'm not sure. For me if I have the affectedNode list from the new signature and the list of the nodes already affected by present signature, all I should do is an intersection check ? Which would give something like this:
```
Node parentSignature = getParentNodeOfSignature();
Set<Node> affectedContentNodes = getAffectedContent(parentSignature);
for (Node signatureNode: existingsignature) {
    Set<Node> coveredContent = getCovertedContent(signatureNode);
    if (coveredContent.retainAll(affectedContentNode).size() > 0 ) continue;
    assertDoesNotContainEnvelopedTransform(signatureNode);
}
```
What do you think about this? 
KR,
Pierre

**Comment by bsanchezb** [comment]
Additionally, try to avoid temporary documentDom assignment, if possible. I understand why you do it, but maybe instead of modifying a global variable, it would be better to provide the Document dom directly to the method, for instance:
```
Node parentSignatureNode = getParentNodeOfSignature(dom);
```
and
```
protected Node getParentNodeOfSignature(Document documentDom) {
   ...
}
```

**Comment by Pierre-Lemaigre** [comment]
> I would say you do not need to execute _getAffectedContent()_ on the _parentSignature_ Node. The goal is to simply ensure that the _parentSignature_ Node itself is not part of the covered content by the existing signatures. If an existing signature covers a child or a nested child of the _parentSignature_ Node, addition of a new signature within the _parentSignature_ Node will not affect that child (imagine you build a path from the child to the root element, it will stay unchanged, as you just add a new sibling to one of the elements in the root), thus it will not impact the existing signature either.

Yes, but getAffectedContent look for the Parent node of the parent node of the signature recursively. I think that is the other way around but i'm not sure.

**Comment by Pierre-Lemaigre** [comment]
> Additionally, try to avoid temporary documentDom assignment, if possible. I understand why you do it, but maybe instead of modifying a global variable, it would be better to provide the Document dom directly to the method, for instance:
> 
> ```
> Node parentSignatureNode = getParentNodeOfSignature(dom);
> ```
> 
> and
> 
> ```
> protected Node getParentNodeOfSignature(Document documentDom) {
>    ...
> }
> ```

I totally approve, but for this i would need to refactor lot of methods and i'm not familiar with the codebase, and thus really uncomfortable to modify that much code which is used lot of others place (I dont want to break your project to be honest). So I can do the solution with the global var modifier and then let you do this modification?

**Comment by bsanchezb** [comment]
> Yes, but getAffectedContent look for the Parent node of the parent node of the signature recursively. I think I do the check the other way around of your solution but i'm not sure.

Ok, it makes sense then. I overlooked it indeed. But you may actually do it in this way or another. So it is **either** you get the parent Node chain of the new signature and compare with the Node covered by the existing signature directly, **or** you extract the Node of the existing signature **including all its children recursively** and compare it only against the _parentSignatureNode_.
One way or another it should work.

> I totally approve, but for this i would need to refactor lot of methods and i'm not familiar with the codebase, and thus really uncomfortable to modify that much code which is used lot of others place (I dont want to break your project to be honest). So I can do the solution with the global var modifier and then let you do this modification?

No problem. I may refactor it after.

**Comment by Pierre-Lemaigre** [comment]
Alright, another question, is their a function to get the node referenced by a Signature. Somehow i can't find it.

**Comment by bsanchezb** [comment]
Please use the method below:
```
NodeList referenceNodeList = DSSXMLUtils.getReferenceNodeList(signatureNode);
```

KR,
Aleksandr

**Comment by bsanchezb** [comment]
Hi Pierre,

The latest change looks good.

I did some minor modifications, to resolve the issue with a temp variable assignment, aligned code to project's style and added more unit tests.

I will merge the branch soon.

KR,
Aleksandr

**Comment by Pierre-Lemaigre** [comment]
Hello Aleksandr,

Thanks for all your help. I was delighted to contribute to this project, and whish you the best

KR,
Pierre

**Comment by bsanchezb** [comment]
Thank you too for the contribution!

_P.S. Just to keep things together, this is my commit with minor changes and unit tests: https://github.com/esig/dss/commit/e6239c07e88c2aa708df250a10ab8169d532d722_

**Pull request merged**
